### ISSUE TITLE
Crash in release builds if I open a child window and close the main window

### ISSUE THREAD

**Issue by nyanpasu64** [nativeshell/examples#9]
I'm running this repo, latest main d385acefcc2405ddb863f79e3ccdb4479891008c, on Linux.

If I `cargo run --release`, then click "Open in New Window" or "Show Other Window" (since they're non-modal), then close the main window with the child still open, the process will segfault.

- There is an inconsistent delay before the program crashes. In the case of "Show Other Window", the segfault happens *after* the "Call method on parent window" button is grayed out.
- The segfault does not occur on debug builds of Cargo+Flutter through `cargo run`. (I don't know how to control Rust and Flutter debugging separately.)

Stack trace is as follows (sadly it's a bit useless since libflutter_linux_gtk.so has no symbols):

<details>

```
(gdb) bt
#0  0x00007ffff7dc5bf6 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#1  0x00007ffff7db5526 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#2  0x00007ffff7dc6705 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#3  0x00007ffff7f43934 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#4  0x00007ffff7b4bf29 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#5  0x00007ffff7c4ccb6 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#6  0x00007ffff7d56197 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#7  0x00007ffff7b26ee6 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#8  0x00007ffff7b25579 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#9  0x00007ffff7b3cb81 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#10 0x00007ffff768d073 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#11 0x00007ffff7692f46 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#12 0x00007ffff768cf11 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#13 0x00007ffff7692715 in  () at /home/nyanpasu64/code/nativeshell-examples/target/release/lib/libflutter_linux_gtk.so
#14 0x00007ffff6494259 in start_thread () at /usr/lib/libpthread.so.0
#15 0x00007ffff63b65e3 in clone () at /usr/lib/libc.so.6
```
</details>

**Flutter version:**

Flutter 2.3.0-17.0.pre.412 • channel master • https://github.com/flutter/flutter.git
Framework • revision 66b8f601e8 (62 minutes ago) • 2021-06-20 19:04:02 -0400
Engine • revision 1eb8a34a39
Tools • Dart 2.14.0 (build 2.14.0-228.0.dev)

**System info:**

Operating System: Arch Linux
KDE Plasma Version: 5.22.1
KDE Frameworks Version: 5.83.0
Qt Version: 5.15.2
Kernel Version: 5.12.11-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 730/PCIe/SSE2

**Comment by knopp** [comment]
Hi, this is a known issue, it is tracked here: https://github.com/flutter/flutter/issues/84908
The PR to fix it is being discussed here: https://github.com/flutter/engine/pull/26835
